# Generated by Django 4.2.5 on 2024-03-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_appointment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doc_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
