# Generated by Django 4.2.5 on 2024-03-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_appointment_doctor_appointment_doc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='apt_date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='dept',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
