# Generated by Django 4.2.5 on 2024-04-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='services',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
